server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: microservicios

  application:
    name: CALIFICACION-SERVICE

  config:
    import: configserver:http://127.0.0.1:8085
  profiles:
    active: default