server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservicios
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USUARIO-SERVICE

  config:
    import: configserver:http://127.0.0.1:8085
  profiles:
    active: default

management:
  health:
    circuitbreakers:
      enable: true
    enpoints:
      web:
        exposure:
          include: health

    enpoint:
      health:
        show-details: always


resilience4j:
  circuitBreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

    retry:
      instances:
        ratingHotelServices:
          max-attempts: 3
          wait-duration: 5s