global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.7:8087']
        labels:
          application: 'Producto Service Application'
  - job_name: 'inventario-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.7:8082']
        labels:
          application: 'Inventario Service Application'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.7:8089']
        labels:
          application: 'Order Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.7:8086']
        labels:
          application: 'Notificacion Service Application'
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.7:8079' ]
        labels:
          application: 'Message Service Application'